# Generated by Django 2.0.6 on 2018-06-26 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ts', models.DateTimeField(default='1970-01-01 00:00:00')),
                ('game_outcome', models.IntegerField(default=0)),
                ('ranked_status', models.IntegerField(default=0)),
                ('players', models.CharField(default='NULL', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='player',
            field=models.ManyToManyField(to='api.Player'),
        ),
    ]
