# Generated by Django 2.0.6 on 2018-06-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='account_id',
            field=models.IntegerField(default=-999),
        ),
    ]
